name: server

on:
  workflow_run:
    workflows: ["docker"]
    types:
      - completed

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script_stop: true
          script: |
            cd /home/$USER/Projects/Punch
            git pull
            docker-compose down
            docker rmi mraddict063/joinus
            docker-compose up -d
